name = "hezardastan-sours"
main = ".open-next/worker.js"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "hezar-dastan-test-db"
database_id = "54954986-46df-4c71-ae2d-45b4f294d762"
