import { Article, DashboardStats, Source } from './types';

export const mockDashboardStats: DashboardStats = {
  activeSourcesCount: 14,
  totalSourcesCount: 16,
  totalArticlesCount: 1842,
  todayArticlesCount: 128,
  processingJobsCount: 4,
  failedJobsCount: 3,
  lastRunTime: '۱۰ دقیقه پیش (۱۶:۰۵)',
  nextRunTime: '۵ دقیقه دیگر (۱۶:۲۰)',
  sourcesCheckedCount: 14,
  newArticlesCount: 23,
  errorsCount: 1,
  fullContentSuccessRate: 98.2,
};

export const mockSources: Source[] = [
  {
    id: 'src-1',
    name: 'خبرگزاری ایسنا',
    slug: 'isna',
    baseUrl: 'https://www.isna.ir',
    feedUrl: 'https://www.isna.ir/rss',
    discoveryType: 'rss',
    pollingIntervalMinutes: 15,
    isActive: true,
    healthStatus: 'healthy',
    consecutiveFailures: 0,
    extractionRulesJson: '{"title": "h1.title", "content": ".item-text", "images": ".item-text img"}',
    lastCrawledAt: '۱۴۰۳/۰۶/۱۴ - ۱۶:۰۵',
    articlesCount: 542,
    createdAt: '۱۴۰۳/۰۵/۰۱',
  },
  {
    id: 'src-2',
    name: 'خبرگزاری ایرنا',
    slug: 'irna',
    baseUrl: 'https://www.irna.ir',
    feedUrl: 'https://www.irna.ir/rss',
    discoveryType: 'rss',
    pollingIntervalMinutes: 15,
    isActive: true,
    healthStatus: 'healthy',
    consecutiveFailures: 0,
    extractionRulesJson: '{"title": "h1.header-title", "content": ".item-body", "images": ".item-body img"}',
    lastCrawledAt: '۱۴۰۳/۰۶/۱۴ - ۱۶:۰۵',
    articlesCount: 489,
    createdAt: '۱۴۰۳/۰۵/۰۱',
  },
  {
    id: 'src-3',
    name: 'زومیت (Zoomit)',
    slug: 'zoomit',
    baseUrl: 'https://www.zoomit.ir',
    feedUrl: 'https://www.zoomit.ir/feed/',
    discoveryType: 'rss',
    pollingIntervalMinutes: 30,
    isActive: true,
    healthStatus: 'healthy',
    consecutiveFailures: 0,
    extractionRulesJson: '{"title": "h1", "content": "article.article-content", "images": "article img"}',
    lastCrawledAt: '۱۴۰۳/۰۶/۱۴ - ۱۵:۵۰',
    articlesCount: 318,
    createdAt: '۱۴۰۳/۰۵/۱۰',
  },
  {
    id: 'src-4',
    name: 'دیجیاتو (Digiato)',
    slug: 'digiato',
    baseUrl: 'https://digiato.com',
    feedUrl: 'https://digiato.com/feed',
    discoveryType: 'rss',
    pollingIntervalMinutes: 30,
    isActive: true,
    healthStatus: 'healthy',
    consecutiveFailures: 0,
    extractionRulesJson: '{"title": "h1.entry-title", "content": ".entry-content", "images": ".entry-content img"}',
    lastCrawledAt: '۱۴۰۳/۰۶/۱۴ - ۱۵:۵۰',
    articlesCount: 265,
    createdAt: '۱۴۰۳/۰۵/۱۵',
  },
  {
    id: 'src-5',
    name: 'یورونیوز فارسی',
    slug: 'euronews-fa',
    baseUrl: 'https://per.euronews.com',
    feedUrl: 'https://per.euronews.com/rss?level=theme&name=news',
    discoveryType: 'rss',
    pollingIntervalMinutes: 15,
    isActive: true,
    healthStatus: 'degraded',
    consecutiveFailures: 2,
    extractionRulesJson: '{"title": "h1.c-article-title", "content": ".c-article-content", "images": ".c-article-content img"}',
    lastCrawledAt: '۱۴۰۳/۰۶/۱۴ - ۱۶:۰۵',
    articlesCount: 198,
    createdAt: '۱۴۰۳/۰۵/۲۰',
  },
  {
    id: 'src-6',
    name: 'پایگاه خبری تابناک',
    slug: 'tabnak',
    baseUrl: 'https://www.tabnak.ir',
    feedUrl: 'https://www.tabnak.ir/fa/rss/allnews',
    discoveryType: 'rss',
    pollingIntervalMinutes: 60,
    isActive: false,
    healthStatus: 'failing',
    consecutiveFailures: 5,
    extractionRulesJson: '{"title": ".title", "content": ".body", "images": ".body img"}',
    lastCrawledAt: '۱۴۰۳/۰۶/۱۴ - ۱۱:۰۰',
    articlesCount: 30,
    createdAt: '۱۴۰۳/۰۶/۰۱',
  },
  {
    id: 'src-7',
    name: 'بلاگ فناوری تک‌کرانچ فارسی',
    slug: 'techcrunch-fa',
    baseUrl: 'https://techblog.example.com',
    feedUrl: 'https://techblog.example.com/sitemap-articles.xml',
    discoveryType: 'sitemap',
    pollingIntervalMinutes: 60,
    isActive: true,
    healthStatus: 'healthy',
    consecutiveFailures: 0,
    lastCrawledAt: '۱۴۰۳/۰۶/۱۴ - ۱۵:۰۰',
    articlesCount: 84,
    createdAt: '۱۴۰۳/۰۶/۰۵',
  },
  {
    id: 'src-8',
    name: 'پرتال علمی و پژوهشی دانشگاه',
    slug: 'science-portal',
    baseUrl: 'https://research.example.edu',
    feedUrl: 'https://research.example.edu/articles',
    discoveryType: 'listing',
    pollingIntervalMinutes: 120,
    isActive: true,
    healthStatus: 'healthy',
    consecutiveFailures: 0,
    lastCrawledAt: '۱۴۰۳/۰۶/۱۴ - ۱۴:۳۰',
    articlesCount: 42,
    createdAt: '۱۴۰۳/۰۶/۰۷',
  },
];

export const mockArticles: Article[] = [
  {
    id: 'art-101',
    sourceId: 'src-3',
    sourceName: 'زومیت (Zoomit)',
    sourceSlug: 'zoomit',
    url: 'https://www.zoomit.ir/software/438921-cloudflare-workers-d1-architecture/',
    normalizedUrl: 'https://www.zoomit.ir/software/438921-cloudflare-workers-d1-architecture',
    originalTitle: 'معماری سرورلس ابری با Cloudflare Workers و دیتابیس D1 | زومیت',
    cleanedTitle: 'معماری سرورلس ابری با Cloudflare Workers و دیتابیس D1',
    author: 'مهرداد عیسی‌لو',
    canonicalUrl: 'https://www.zoomit.ir/software/438921-cloudflare-workers-d1-architecture',
    publishedAt: '۱۴۰۳/۰۶/۱۴ - ۱۵:۳۰',
    discoveredAt: '۱۴۰۳/۰۶/۱۴ - ۱۵:۵۰',
    language: 'fa',
    processingStatus: 'ready_for_processor',
    retryCount: 0,
    hasFullContent: true,
    content: {
      articleId: 'art-101',
      plainText: `پلتفرم کلودفلر با معرفی دیتابیس رابطه‌ای D1 و سیستم‌های صف پیام (Queues)، انقلابی در توسعه وب در لبه شبکه ایجاد کرده است. در این بررسی عمیق به نحوه مهاجرت از معماری‌های سنتی به معماری‌های توزیع‌شده با تاخیر زیر ۱۰ میلی‌ثانیه می‌پردازیم.
کلودفلر D1 که بر پایه موتور سبک SQLite توسعه یافته، اجازه می‌دهد پایگاه داده‌های SQL ساختاریافته بدون نیاز به مدیریت سرور در ۳۰۰ دیتاسنتر جهان تکرار شوند. ویژگی اصلی این سیستم یکپارچگی با ورکرها بدون لایه‌های رابط پیچیده است.
علاوه بر این، ترکیب Cloudflare Queues برای برون‌سپاری بارهای پردازشی سنگین مثل خزش صفحات وب، خطاهای سرورلس ناشی از تایم‌اوت را به صفر می‌رساند.`,
      cleanedContentHtml: `<p>پلتفرم کلودفلر با معرفی دیتابیس رابطه‌ای D1 و سیستم‌های صف پیام (Queues)، انقلابی در توسعه وب در لبه شبکه ایجاد کرده است.</p><p>کلودفلر D1 که بر پایه موتور سبک SQLite توسعه یافته، اجازه می‌دهد پایگاه داده‌های SQL ساختاریافته بدون نیاز به مدیریت سرور در ۳۰۰ دیتاسنتر جهان تکرار شوند.</p><p>علاوه بر این، ترکیب Cloudflare Queues برای برون‌سپاری بارهای پردازشی سنگین مثل خزش صفحات وب، خطاهای سرورلس ناشی از تایم‌اوت را به صفر می‌رساند.</p>`,
      summary: 'بررسی عمیق معماری سرورلس کلودفلر با دیتابیس توزیع‌شده D1 و صف وظایف Queues.',
      wordCount: 840,
      readingTimeMinutes: 4,
      contentHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    },
    seo: {
      articleId: 'art-101',
      seoTitle: 'معماری سرورلس ابری با Cloudflare Workers و دیتابیس D1',
      seoDescription: 'بررسی تخصصی قابلیت‌های دیتابیس توزیع‌شده D1 کلودفلر و سیستم صف برای اپلیکیشن‌های با مقیاس بالا.',
      seoKeywords: ['کلودفلر', 'کلودفلر ورکرز', 'دیتابیس D1', 'سرورلس', 'پایگاه داده لبه'],
      canonicalUrl: 'https://www.zoomit.ir/software/438921-cloudflare-workers-d1-architecture',
      metaRobots: 'index, follow, max-image-preview:large',
      ogTitle: 'معماری سرورلس ابری با Cloudflare Workers و دیتابیس D1',
      ogDescription: 'بررسی تخصصی قابلیت‌های دیتابیس توزیع‌شده D1 کلودفلر و سیستم صف برای اپلیکیشن‌های با مقیاس بالا.',
      ogImage: 'https://picsum.photos/seed/cloudflare/800/450',
      ogType: 'article',
      twitterCard: 'summary_large_image',
      schemaType: 'NewsArticle',
    },
    images: [
      {
        id: 'img-1',
        articleId: 'art-101',
        imageUrl: 'https://picsum.photos/seed/cloudflare/800/450',
        altText: 'نمودار معماری Cloudflare D1 و Workers',
        caption: 'معماری توزیع لبه با دیتابیس D1',
        credit: 'تیم فنی زومیت',
        isFeatured: true,
        sortOrder: 1,
        width: 1200,
        height: 675,
      },
      {
        id: 'img-2',
        articleId: 'art-101',
        imageUrl: 'https://picsum.photos/seed/sqlite/800/450',
        altText: 'مقایسه عملکرد SQLite با دیتابیس‌های سنتی',
        caption: 'نمودار تاخیر پاسخگویی بر حسب میلی‌ثانیه',
        isFeatured: false,
        sortOrder: 2,
        width: 800,
        height: 450,
      },
    ],
  },
  {
    id: 'art-102',
    sourceId: 'src-1',
    sourceName: 'خبرگزاری ایسنا',
    sourceSlug: 'isna',
    url: 'https://www.isna.ir/news/1403061408892/technology-summit-ai-iran/',
    normalizedUrl: 'https://www.isna.ir/news/1403061408892/technology-summit-ai-iran',
    originalTitle: 'برگزاری همایش بین‌المللی هوش مصنوعی و اقتصاد داده در تهران - ایسنا',
    cleanedTitle: 'برگزاری همایش بین‌المللی هوش مصنوعی و اقتصاد داده در تهران',
    author: 'تحریریه علمی و فناوری ایسنا',
    canonicalUrl: 'https://www.isna.ir/news/1403061408892/technology-summit-ai-iran',
    publishedAt: '۱۴۰۳/۰۶/۱۴ - ۱۵:۱۰',
    discoveredAt: '۱۴۰۳/۰۶/۱۴ - ۱۶:۰۵',
    language: 'fa',
    processingStatus: 'ready_for_processor',
    retryCount: 0,
    hasFullContent: true,
    content: {
      articleId: 'art-102',
      plainText: `همایش سالانه هوش مصنوعی و اقتصاد دیجیتال با حضور نخبگان علمی، کارآفرینان و مدیران ارشد مراکز داده امروز در دانشگاه صنعتی شریف آغاز به کار کرد.
در این نشست تخصصی، راهکارهای ذخیره‌سازی ابری امن، داده‌های ساختاریافته و استانداردسازی زبان فارسی در پایگاه‌های داده مورد تحلیل قرار گرفت.
سخنرانان بر ضرورت ایجاد خطوط لوله داده‌ای تمیز برای آموزش مدل‌های محلی تاکید کردند.`,
      cleanedContentHtml: `<p>همایش سالانه هوش مصنوعی و اقتصاد دیجیتال با حضور نخبگان علمی، کارآفرینان و مدیران ارشد مراکز داده امروز در دانشگاه صنعتی شریف آغاز به کار کرد.</p><p>در این نشست تخصصی، راهکارهای ذخیره‌سازی ابری امن، داده‌های ساختاریافته و استانداردسازی زبان فارسی در پایگاه‌های داده مورد تحلیل قرار گرفت.</p>`,
      summary: 'آغاز به کار رویداد بین‌المللی هوش مصنوعی و زیرساخت‌های داده در دانشگاه صنعتی شریف.',
      wordCount: 512,
      readingTimeMinutes: 3,
      contentHash: 'a7c9f8892be1198cda3829019283471928374192837419283741928374192834',
    },
    seo: {
      articleId: 'art-102',
      seoTitle: 'همایش هوش مصنوعی و اقتصاد داده در تهران | ایسنا',
      seoDescription: 'گزارش کامل افتتاحیه نشست ملی زیرساخت‌های ابری و هوش مصنوعی.',
      seoKeywords: ['هوش مصنوعی', 'دانشگاه شریف', 'اقتصاد داده', 'اخبار فناوری'],
      canonicalUrl: 'https://www.isna.ir/news/1403061408892/technology-summit-ai-iran',
      metaRobots: 'index, follow',
      ogTitle: 'همایش هوش مصنوعی و اقتصاد داده در تهران',
      ogDescription: 'گزارش کامل افتتاحیه نشست ملی زیرساخت‌های ابری و هوش مصنوعی.',
      ogImage: 'https://picsum.photos/seed/summit/800/450',
      ogType: 'article',
      twitterCard: 'summary_large_image',
    },
    images: [
      {
        id: 'img-3',
        articleId: 'art-102',
        imageUrl: 'https://picsum.photos/seed/summit/800/450',
        altText: 'سالن همایش هوش مصنوعی در دانشگاه شریف',
        caption: 'تصویر مراسم افتتاحیه با حضور اساتید',
        isFeatured: true,
        sortOrder: 1,
      },
    ],
  },
  {
    id: 'art-103',
    sourceId: 'src-4',
    sourceName: 'دیجیاتو (Digiato)',
    sourceSlug: 'digiato',
    url: 'https://digiato.com/tech-news/new-fiber-optic-project-expansion/',
    normalizedUrl: 'https://digiato.com/tech-news/new-fiber-optic-project-expansion',
    originalTitle: 'گسترش پوشش فیبر نوری در ۸ کلان‌شهر کشور کلید خورد - دیجیاتو',
    cleanedTitle: 'گسترش پوشش فیبر نوری در ۸ کلان‌شهر کشور کلید خورد',
    author: 'امیر مستکین',
    canonicalUrl: 'https://digiato.com/tech-news/new-fiber-optic-project-expansion',
    publishedAt: '۱۴۰۳/۰۶/۱۴ - ۱۴:۴۵',
    discoveredAt: '۱۴۰۳/۰۶/۱۴ - ۱۵:۵۰',
    language: 'fa',
    processingStatus: 'parsed',
    retryCount: 0,
    hasFullContent: true,
    content: {
      articleId: 'art-103',
      plainText: `بر اساس اعلام اپراتورهای شبکه، فاز دوم اتصال منازل و کسب‌وکارها به شبکه فیبر نوری با سرعت بیش از ۳۰۰ مگابیت بر ثانیه آغاز شد. این پروژه قرار است تا پایان سال پوشش خانگی را به ۴ میلیون مشترک برساند.`,
      cleanedContentHtml: `<p>بر اساس اعلام اپراتورهای شبکه، فاز دوم اتصال منازل و کسب‌وکارها به شبکه فیبر نوری با سرعت بیش از ۳۰۰ مگابیت بر ثانیه آغاز شد.</p>`,
      summary: 'کلید خوردن مرحله جدید توسعه اتصالات فیبر نوری فوق‌سریع در ۸ کلان‌شهر.',
      wordCount: 380,
      readingTimeMinutes: 2,
      contentHash: 'b6f8a9e71b23908acbf982347901823749018237490182374901823749018237',
    },
    seo: {
      articleId: 'art-103',
      seoTitle: 'توسعه فیبر نوری در کلان‌شهرها | دیجیاتو',
      seoDescription: 'جزئیات فاز جدید اتصال پهن‌باند فیبر نوری در کشور.',
      seoKeywords: ['فیبر نوری', 'اینترنت پرسرعت', 'دیجیاتو'],
      canonicalUrl: 'https://digiato.com/tech-news/new-fiber-optic-project-expansion',
      metaRobots: 'index, follow',
      ogTitle: 'گسترش پوشش فیبر نوری در ۸ کلان‌شهر',
      ogDescription: 'جزئیات فاز جدید اتصال پهن‌باند فیبر نوری در کشور.',
      ogImage: 'https://picsum.photos/seed/fiber/800/450',
      ogType: 'article',
      twitterCard: 'summary',
    },
    images: [
      {
        id: 'img-4',
        articleId: 'art-103',
        imageUrl: 'https://picsum.photos/seed/fiber/800/450',
        altText: 'کابل‌های فیبر نوری مخابراتی',
        titleText: 'کابل‌کشی فیبر نوری پروژه ملی',
        caption: 'تجهیزات زیرساختی فیبر نوری',
        isFeatured: true,
        sortOrder: 1,
        width: 1024,
        height: 576,
      },
    ],
  },
  {
    id: 'art-104',
    sourceId: 'src-2',
    sourceName: 'خبرگزاری ایرنا',
    sourceSlug: 'irna',
    url: 'https://www.irna.ir/news/85591024/renewables-solar-power-plant-isfahan/',
    normalizedUrl: 'https://www.irna.ir/news/85591024/renewables-solar-power-plant-isfahan',
    originalTitle: 'بهره‌برداری از بزرگترین نیروگاه خورشیدی فتوولتائیک فلات مرکزی - ایرنا',
    cleanedTitle: 'بهره‌برداری از بزرگترین نیروگاه خورشیدی فتوولتائیک فلات مرکزی',
    author: 'خبرنگار ایرنا در اصفهان',
    canonicalUrl: 'https://www.irna.ir/news/85591024/renewables-solar-power-plant-isfahan',
    publishedAt: '۱۴۰۳/۰۶/۱۴ - ۱۴:۲۰',
    discoveredAt: '۱۴۰۳/۰۶/۱۴ - ۱۶:۰۵',
    language: 'fa',
    processingStatus: 'queued',
    retryCount: 0,
    hasFullContent: false,
  },
  {
    id: 'art-105',
    sourceId: 'src-5',
    sourceName: 'یورونیوز فارسی',
    sourceSlug: 'euronews-fa',
    url: 'https://per.euronews.com/2024/09/03/eu-tech-regulations-digital-markets-act/',
    normalizedUrl: 'https://per.euronews.com/2024/09/03/eu-tech-regulations-digital-markets-act',
    originalTitle: 'اجرای مقررات جدید بازارهای دیجیتال اروپا و بازنگری در حریم خصوصی کاربران',
    cleanedTitle: 'اجرای مقررات جدید بازارهای دیجیتال اروپا و بازنگری در حریم خصوصی کاربران',
    author: 'سرویس بین‌الملل یورونیوز',
    canonicalUrl: 'https://per.euronews.com/2024/09/03/eu-tech-regulations-digital-markets-act',
    publishedAt: '۱۴۰۳/۰۶/۱۴ - ۱۳:۵۰',
    discoveredAt: '۱۴۰۳/۰۶/۱۴ - ۱۶:۰۵',
    language: 'fa',
    processingStatus: 'failed',
    retryCount: 2,
    lastError: 'خطای ۴۰۳: مسدودسازی درخواست توسط دیوار آتش مبدا (Cloudflare Challenge)',
    hasFullContent: false,
  },
];
